webtalk_init -webtalk_dir E:/project/FPGA/ai1/05.my_btn_debounce/05.my_btn_debounce.sim/sim_1/behav/xsim/xsim.dir/tb_my_btn_debounce_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Feb 12 20:19:00 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2021.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3247384" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "52960b60-179c-4a3b-ace4-5562febd40c7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "abc6436c622d4a058c9ac2d9c94e42d0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "35" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "137001200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "5.58_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17660_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4031240070 -regid "" -xml E:/project/FPGA/ai1/05.my_btn_debounce/05.my_btn_debounce.sim/sim_1/behav/xsim/xsim.dir/tb_my_btn_debounce_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/project/FPGA/ai1/05.my_btn_debounce/05.my_btn_debounce.sim/sim_1/behav/xsim/xsim.dir/tb_my_btn_debounce_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/project/FPGA/ai1/05.my_btn_debounce/05.my_btn_debounce.sim/sim_1/behav/xsim/xsim.dir/tb_my_btn_debounce_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
